name: Update Weather

on:
  schedule:
    - cron: "*/5 * * * *" # 每5分鐘更新一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Weather Data
        run: |
          export TZ=Asia/Taipei
          curl -s "https://api.openweathermap.org/data/2.5/weather?q=Taipei&appid=${{ secrets.OPENWEATHER_KEY }}&units=metric&lang=zh_tw" \
          | jq --arg time "$(date '+%Y-%m-%d %H:%M:%S')" '. + {updated_at: $time}' > weather.json

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add weather.json
          git commit -m "Update weather data" || echo "No changes to commit"
          git push
